### ISSUE TITLE
nicer mwe_lemma

### ISSUE THREAD

**Issue by Ansa211** [natalink/mwe_noske#6]
The current implementation uses a concatenation of the lemmas of the nodes in the order in which they appear in the sentence. There is no unification with respect to word order, and the resulting lemma does not correspond to the lemma that a human would intuitively assign to the given MWE.

Some ideas how to improve this are as follows:

- [x]  reviewer's comment (I agree): "VMWE separated by underscore: be\_in\_doubt Not wrong, but why not simply separated by spaces?"
- [ ] use the lemma of the MWE head, but the form of MWE children
   - *jít o vpadnutí do zad*, not *jít o vpadnutí do záda*
     *univerzita Karlova*, not *univerzita Karlův*
- [ ] put the head first in the lemma
   + good for free word-order languages:
       both *Univerzita Karlova* and *Karlova Univerzita* should get the same lemma
       the sentence *o vpadnutí do zad ale tentokrát nešlo* gets the same lemma as with the normal word-order
   - bad for languages with strict word-order
         e.g. in English "NOUN NOUN" MWE's the head is normally second: *cheese cake* would be lemmatized as *cake cheese*, BAD
   - maybe a good compromise would be to limit this rule to cases with verbal heads?

**Comment by natalink** [comment]
> but why not simply separated by spaces?

I was always very cautious about spaces in the vertical. Hope you guys know that it works and compiles. Otherwise I agree and I'll change it.

>  use the lemma of the MWE head, but the form of MWE children  &&   put the head first in the lemma

I agree that it makes sense, but at this stage it seems overcompicating to me. (Btw, we have only verbal MWEs here)
Otherwise this issue should to be consulted with the core PARSEME group what can we do about it. They took decision to encode VMWEs with head being the first word regardless of POS. So now if we start writing some script smth like  ``` if pos eq "VERB" and ord ne "1" ; do put verb_lemma first  ```, we may run into some problems which PARSEME members have already encountered maybe for other languages.  I'd rather just stick for whatever they have in data. 

Initially I didn't even planned to introduced smth like **vmwe_lemma**, but it seemed it might be helpful in some cases.  Maybe better just leave it as a mwe_form???. Anyway, we may write it into _future work_ section. 
   
If people start using this tool, we can get feedback from them and discuss those points with end-users what exactly they need and implement your suggestion.

**Comment by natalink** [comment]
Just an observation if we want to extract VERB feature in order to manipulate with verbs: BG, HE and LT do not have .conllu file. For IT and HU the fourth column attributes - POS - is different from others (V instead of **VERB**?), for RO and SL there is a treetagger-style positional attribute, in TR - Verb.

**Comment by natalink** [comment]
Also, in case of e.g. ```mít nápady``` (have ideas), we want to have a lemma as ```mít nápad```(have idea) or ```mít nápady```(have ideas)?

**Comment by Ansa211** [comment]
People from the PARSEME group are our main audience so if they have reached a consensus about lemmatization, we should use the same rules to make the data more accessible for them.

It's not quite clear to me if introducing either `mwe_lemma` or `mwe_form` is useful; but I definitely think that lemma is more useful than form. It should be standardized, so probably `mít nápady` (have ideas) should have lemma `mít nápad` (have an idea). But can we formulate and implement such rules for all 18 languages? We would need a morphological analyzer AND a tool for generating the singular forms from their tags...

**Comment by natalink** [comment]
I take a lemma from a .conllu file, so theoretically we can do this and exclude languages without .conllu. But the solution in lemma _verb first_ may have some issues in other non-European languages like Japanese. So I would leave it as it is now - just lemmas in the same order they occurred in the sentence - though it's not the best solution for most European languages. Later we can change based on user feedback.

**Comment by Ansa211** [comment]
Because of the issue reported in #7, we do not know which word of the VMWE is the head. Therefore, there is currently now way how to implement the remaining two points of my original suggestion, even if we wanted to.

**Comment by Ansa211** [comment]
Note: in the Spanish data, the lemma is present in the column that we currently call `misc`, e.g.:

```
22	en	en	ADP	ADP	AdpType=Prep	25	case	_	MWE=en_materia_de|MWEPOS=ADP
23	materia	materia	NOUN	NOUN	_	22	mwe	_	_
24	de	de	ADP	ADP	AdpType=Prep	22	mwe	_	_
```

**Comment by languagerecipes** [comment]
Can you please explain the problem rather on top of the thread when you create an issue? I cannot see a problem statement

**Comment by Ansa211** [comment]
I did explain it with lots of details in the first comment! If that's not enough, I don't know how I can help. The current implementation leads to lemmas that are not unified in any way (e.g. with respect to word-order). 

My last comment is something not to forget about if we ever go back to this, namely that the Spanish annotation contains some kind of MWE lemmas already and we might want to use them instead of the approximation we can code.

**Comment by languagerecipes** [comment]
I still do not know what is the problem, but anyway, the PARSEME tsv files must be taken as the reference, if CONLL-U is missing, then the vertical file will contain ``-'' or ``_'' whichever is common for Kontext and NoSKe must be used.

Also, I have noticed that the  CONLL-U files in the PARSEME package are not necessarily CONLL-U but just some vertical file, e.g., the tag set used are not similar across languages etc.

**Comment by Ansa211** [comment]
You noticed this issue is closed because we decided NOT to do it, right?
Also, not every "issue" is a problem. It may be an idea for improvement.

**Comment by languagerecipes** [comment]
have you considered the fact that in some languages , some of the annotated
vmwes do not have a verb head?! (whether this due to error or not is
another matter, but e.g. look into HU data, examples can be found in almost
for all the languages)
